//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haggling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Haggling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haggling.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        internal static string LAUNCH_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("LAUNCH_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var done = arguments[arguments.length - 1];
        ///var times = arguments[0];
        ///var interval = arguments[1];
        ///var count = arguments[2];
        ///var prices = arguments[3];
        ///var quantities = arguments[4];
        ///var symbols = arguments[5];
        ///var sides = arguments[6];
        ///var token = $.md5(document.cookie.match(&apos;CSRFToken=\.+?;&apos;)[0].split(&apos;=&apos;)[1].replace(&apos;;&apos;, &apos;&apos;));
        ///for (var i = 0; i &lt; count; i++) {
        ///	var request = () =  &gt; {
        ///		var price = prices[i];
        ///		var quantity = quantities[i];
        ///		var symbol = symbols[i];
        ///		var side = sides[i];        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var done = arguments[arguments.length - 1];
        ///var symbol = arguments[0];
        ///var quantity = arguments[1];
        ///var token = $.md5(document.cookie.match(&apos;CSRFToken=\.+?;&apos;)[0].split(&apos;=&apos;)[1].replace(&apos;;&apos;, &apos;&apos;));
        ///$.get(&apos;/api/v1/depth?symbol=&apos; + symbol).then(function (resp) {
        ///	try {
        ///		var depth = JSON.parse(resp);
        ///		var sell = parseFloat(depth.asks[0][0]);
        ///		var buy = parseFloat(depth.bids[0][0]);
        ///		var average = Math.ceil((buy + sell) / 2 * 100) / 100;
        ///		if (average &gt; buy &amp;&amp; average &lt; sell) {
        ///			console.log(averag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sellbuy {
            get {
                return ResourceManager.GetString("sellbuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var done = arguments[arguments.length - 1];
        ///var symbol = arguments[0];
        ///var price = arguments[1];
        ///var token = $.md5(document.cookie.match(&apos;CSRFToken=\.+?;&apos;)[0].split(&apos;=&apos;)[1].replace(&apos;;&apos;, &apos;&apos;));
        ///var start = new Date();
        ///$.ajax({
        ///	type : &apos;POST&apos;,
        ///	url : &apos;/exchange/private/order&apos;,
        ///	data : $.param({
        ///		price : price,
        ///		quantity : 1,
        ///		symbol : symbol,
        ///		side : &apos;BUY&apos;,
        ///		type : &apos;LIMIT&apos;
        ///	}),
        ///	headers : {
        ///		CSRFToken : token
        ///	},
        ///	success : function (resp) {
        ///		done(resp.transactTime - start.getTime()); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动浏览器登录后执行脚本.
        /// </summary>
        internal static string STATUS_CONTENT_BROWSER {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览器关闭，请点击启动重新开启.
        /// </summary>
        internal static string STATUS_CONTENT_BROWSER_CLOSE {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_BROWSER_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择代理商.
        /// </summary>
        internal static string STATUS_CONTENT_CHECK_AGENT {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_CHECK_AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证失败，正在重试，请先登录交易系统.
        /// </summary>
        internal static string STATUS_CONTENT_CHECK_FAILED {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_CHECK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择模式.
        /// </summary>
        internal static string STATUS_CONTENT_CHECK_MODE {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_CHECK_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证成功，点击运行脚本.
        /// </summary>
        internal static string STATUS_CONTENT_CHECK_SUCCESS {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_CHECK_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在验证....
        /// </summary>
        internal static string STATUS_CONTENT_CHECKING {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动客户端登录后验证执行脚本.
        /// </summary>
        internal static string STATUS_CONTENT_CLIENT {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脚本执行失败.
        /// </summary>
        internal static string STATUS_CONTENT_EXECUTE_FAILED {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_EXECUTE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脚本执行停止.
        /// </summary>
        internal static string STATUS_CONTENT_EXECUTE_STOP {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_EXECUTE_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脚本执行成功.
        /// </summary>
        internal static string STATUS_CONTENT_EXECUTE_SUCCESS {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_EXECUTE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在执行脚本.
        /// </summary>
        internal static string STATUS_CONTENT_EXECUTING {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_EXECUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动失败.
        /// </summary>
        internal static string STATUS_CONTENT_FAILED {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入完整的脚本信息，代码、价格、数量.
        /// </summary>
        internal static string STATUS_CONTENT_INPUT {
            get {
                return ResourceManager.GetString("STATUS_CONTENT_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行时间必须大于服务器时间.
        /// </summary>
        internal static string STATUS_TIME_ERROR {
            get {
                return ResourceManager.GetString("STATUS_TIME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证.
        /// </summary>
        internal static string VALIDATE_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("VALIDATE_BUTTON_TITLE", resourceCulture);
            }
        }
    }
}
